BEGIN TRANSACTION;
CREATE TABLE "schedules" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`duration`	INTEGER NOT NULL,
	`active`	INTEGER NOT NULL,
	`recurrent`	INTEGER NOT NULL,
	`rule`	TEXT NOT NULL
);
COMMIT;
